### PR TITLE
Add Docker Healthcheck

### PR DESCRIPTION
**Pull request by JnMik**
Add Docker Healthcheck to prevent connexion refused when scaling up Kong containers in a Docker swarm service.

### CODE REVIEW

**Comment by JnMik** [comment]
Just realized --start-period is only available on Docker 17.05 tho..  So how should we handle this ?

**Comment by hutchic** [comment]
for now leave out `--start-period` the healthchecks prior to 17.05 just loiter in `starting` for a bit longer then ideal which is fine IMO

**Comment by JnMik** [comment]
If I remove --start-period, healthcheck of the first Kong container will fail plenty of times before it gets ready. So swarm will kill the container before he finish running the migrations.

**Comment by hutchic** [comment]
You sure? Earlier versions of Docker / Docker swarm what I would see in services that take time to start is the healthcheck would idle at `healthcheck: starting`

**Comment by JnMik** [comment]
Well it is what I was experiencing yesterday with Docker 17.05.0-ce, build 89658be without the --start-period option. I don't exactly at which moment healthcheck exit "starting" mode and start counting failures. What triggers the change of state ?

**Comment by JnMik** [comment]
Base on what endeepak

**Comment by JnMik** [comment]
Miss-clicked!  Based on what Endeepak mentionned here https://github.com/Mashape/docker-kong/issues/89 I guess I could drop the pull request.

Anyone have interest that I keep it open ?

**Pull request closed without merging**
